[versions]
# Platform expectations
spigot = "1.21.4-R0.1-SNAPSHOT"
paperlib = "1.0.8"

# Plugins
luckperms = "5.4"
worldedit = "7.2.20"
placeholderapi = "2.11.6"
axiompaper = "4.0.1-1.21.1"
# Third Party
annotations = "26.0.2"
authlib = "1.5.25"
bstats = "3.1.0"
fastboard = "2.1.3"
nbt = "1.6.0"
xseries = "13.0.0"
fastutil = "5.0.9"
intellsbom = "1.52"
fawe = "2.13.0"
plotsquared = "7.5.1"

[libraries]
# Platform expectations
spigot = { group = "org.spigotmc", name = "spigot-api", version.ref = "spigot" }
paperlib = { group = "io.papermc", name = "paperlib", version.ref = "paperlib" }

# Plugins
luckperms = { group = "net.luckperms", name = "api", version.ref = "luckperms" }
placeholderapi = { group = "me.clip", name = "placeholderapi", version.ref = "placeholderapi" }
worldedit = { group = "com.sk89q.worldedit", name = "worldedit-core", version.ref = "worldedit" }
axiompaper= {group = "maven.modrinth.workaround", name = "axiom-paper-plugin", version.ref="axiompaper"}

# Third Party
annotations = { group = "org.jetbrains", name = "annotations", version.ref = "annotations" }
authlib = { group = "com.mojang", name = "authlib", version.ref = "authlib" }
bstats = { group = "org.bstats", name = "bstats-bukkit", version.ref = "bstats" }
fastboard = { group = "fr.mrmicky", name = "fastboard", version.ref = "fastboard" }
nbt = { group = "io.github.lumine1909", name = "NBT", version.ref = "nbt" }
xseries = { group = "com.github.cryptomorin", name = "XSeries", version.ref = "xseries" }
fastutil = { group = "fastutil", name = "fastutil", version.ref = "fastutil" }
intellsbom = { group = "com.intellectualsites.bom", name = "bom-newest", version.ref = "intellsbom" }
fawe = { group = "com.fastasyncworldedit", name = "FastAsyncWorldEdit-Core", version.ref = "fawe" }
plotsquared = { group = "com.intellectualsites.plotsquared", name = "plotsquared-core", version.ref = "plotsquared" }